# ML-03 — Frame Your Lane as an ML Task

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. My lane as an ML task (type)

*Classification, clustering, ranking, or scoring — which one, and why?*

Task type: Classification

The goal is to predict whether a customer is likely to purchase a product or not.

This is a classification problem because the output has two possible classes:
Purchase and No Purchase.

## 2. Target or proxy

*What would you predict? Where does that label come from — observed outcome or a defined rule?*

Target: Purchase

The target variable represents whether the customer purchased the product.

Target = 1 → Purchased
Target = 0 → Did not purchase

## 3. Success metric

The success of the ML system can be measured using ranking metrics such as NDCG (Normalized Discounted Cumulative Gain) or Precision@K.

A good model should place the most relevant content higher in the search results. The metric helps evaluate whether the ranking recommendations are useful and accurate.

In [3]:
metric = "nDCG"
print("Primary success metric:", metric)

Primary success metric: nDCG

## 4. The unit of analysis, as a real dataframe

*Load your lane's slice and show it: one row = one what?*

The unit of analysis is one customer.

Each row represents one customer, and the columns contain information about that customer such as their previous activity and purchase behaviour.

The target column is `purchased`:
- 1 = Purchased
- 0 = Did not purchase

In [5]:
from pathlib import Path

print("Current folder:")
print(Path.cwd())

print("\nSearching for the dataset...")
matches = list(Path.cwd().parent.parent.rglob("content_refresh_anonymized.csv"))

print("Found:")
for file in matches:
    print(file)

Current folder:
c:\Users\Bhanu Tejaswini\Downloads\flyrank-ml-internship-starter-tejaswini-main\work\notebooks

Searching for the dataset...
Found:
c:\Users\Bhanu Tejaswini\Downloads\flyrank-ml-internship-starter-tejaswini-main\data\raw\content_refresh_anonymized.csv
c:\Users\Bhanu Tejaswini\Downloads\flyrank-ml-internship-starter-tejaswini-main\flyrank-ml-internship-starter-tejaswini-main\data\raw\content_refresh_anonymized.csv

In [6]:
import pandas as pd
from pathlib import Path

matches = list(Path.cwd().parent.parent.rglob("content_refresh_anonymized.csv"))

print("Dataset found:", matches[0])

df = pd.read_csv(matches[0])

print("Shape:", df.shape)
print("Columns:", df.columns.tolist())

df.head()

Dataset found: c:\Users\Bhanu Tejaswini\Downloads\flyrank-ml-internship-starter-tejaswini-main\data\raw\content_refresh_anonymized.csv
Shape: (30000, 44)
Columns: ['content_id', 'client_id', 'search_volume', 'competition', 'competition_level', 'cpc', 'content_type', 'main_intent', 'word_count', 'char_count', 'provider_used', 'model_used', 'impressions_90d', 'clicks_90d', 'pageviews_90d', 'sessions_90d', 'users_90d', 'engaged_sessions_90d', 'ai_sessions_90d', 'scroll_events_90d', 'days_with_impressions', 'days_with_sessions', 'impressions_last_30d', 'clicks_last_30d', 'sessions_last_30d', 'impressions_prev_30d', 'clicks_prev_30d', 'sessions_prev_30d', 'content_age_days', 'age_tier', 'age_tier_order', 'days_since_last_update', 'freshness_tier', 'word_count_tier', 'char_count_tier', 'ctr', 'avg_position', 'engagement_rate', 'scroll_rate', 'ai_traffic_pct', 'impression_tier', 'position_tier', 'trend_direction', 'trend_pct']

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## 5. Why ML beats a fixed rule here

*What makes the pattern too messy for an if-statement?*

A fixed rule such as "target customers who visited the website more than 5 times" is simple but may not capture different customer behaviours.

ML can combine multiple signals such as previous purchases, website visits, age and engagement to estimate purchase likelihood.

Therefore, ML can provide more flexible and data-driven predictions than a single fixed rule.

In [7]:
import os

for root, dirs, files in os.walk("../../data"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

../../data\raw\content_refresh_anonymized.csv

In [8]:
import os

for root, dirs, files in os.walk("../../data"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

../../data\raw\content_refresh_anonymized.csv

In [9]:
import pandas as pd

data_path = "../../data/raw/content_refresh_anonymized.csv"

df = pd.read_csv(data_path)

df.head()

,content_id,client_id,search_volume,competition,competition_level,cpc,content_type,main_intent,word_count,char_count,...,char_count_tier,ctr,avg_position,engagement_rate,scroll_rate,ai_traffic_pct,impression_tier,position_tier,trend_direction,trend_pct
0,content_304f48230142,client_f369cb89fc,10.0,0.67,HIGH,2.05,keyword article,transactional,3221.0,20457.0,...,15000-25000,0.76,10.6,5.88,4.55,0.0,good,striking,down,-41.4
1,content_a1fb4e703a9e,client_4e07408562,90.0,0.01,LOW,0.05,keyword article,informational,2481.0,15562.0,...,15000-25000,0.05,20.3,0.00,10.00,0.0,good,page_3_5,down,-57.7
2,content_9aa793d4d895,client_7f2253d7e2,0.0,0.00,LOW,0.00,keyword article,informational,3515.0,23643.0,...,15000-25000,0.09,36.5,0.00,28.57,0.0,good,page_3_5,down,-60.9
3,content_331d6c4de07b,client_19581e27de,10.0,0.00,LOW,0.00,keyword article,commercial,NaN,NaN,...,NaN,0.49,6.2,1.28,3.45,0.0,good,page_1,stable,-13.8
4,content_d99b7a2d90ca,client_3fdba35f04,0.0,0.00,LOW,0.00,keyword article,informational,2803.0,17469.0,...,15000-25000,0.13,44.0,0.00,24.29,0.0,good,page_3_5,down,-34.7

## Unit of analysis

The unit of analysis is one content page/document.

Each row in the dataframe represents one content item with different attributes that can help understand search relevance and ranking decisions.

In [10]:
df.shape

(30000, 44)

## Dataset size

The starter dataset contains 30,000 rows and 44 columns.

Each row represents one content item/page record, and the columns contain different attributes that can help analyze search ranking and content performance.

In [11]:
df.columns.tolist()

['content_id',
 'client_id',
 'search_volume',
 'competition',
 'competition_level',
 'cpc',
 'content_type',
 'main_intent',
 'word_count',
 'char_count',
 'provider_used',
 'model_used',
 'impressions_90d',
 'clicks_90d',
 'pageviews_90d',
 'sessions_90d',
 'users_90d',
 'engaged_sessions_90d',
 'ai_sessions_90d',
 'scroll_events_90d',
 'days_with_impressions',
 'days_with_sessions',
 'impressions_last_30d',
 'clicks_last_30d',
 'sessions_last_30d',
 'impressions_prev_30d',
 'clicks_prev_30d',
 'sessions_prev_30d',
 'content_age_days',
 'age_tier',
 'age_tier_order',
 'days_since_last_update',
 'freshness_tier',
 'word_count_tier',
 'char_count_tier',
 'ctr',
 'avg_position',
 'engagement_rate',
 'scroll_rate',
 'ai_traffic_pct',
 'impression_tier',
 'position_tier',
 'trend_direction',
 'trend_pct']

## Target column sketch

For this ranking task, the target/proxy can be a search usefulness score created from observed signals.

Possible signals include:
- impressions_90d
- clicks_90d
- sessions_90d
- engaged_sessions_90d

A higher score would indicate that a content item has stronger search performance signals. This proxy target can help rank content items for search improvement decisions.

## 5. Why ML beats a fixed rule here

A fixed rule cannot handle the complexity of search behavior because different users, queries, and content types have different patterns.

ML can learn from multiple signals in the data and continuously improve ranking decisions. It helps identify useful relationships that are difficult to define manually with simple rules.

## Self-check

Before you submit, confirm each line honestly:

- [X] Every section above is filled — markdown thinking AND the code that backs it
- [X] The notebook runs top to bottom with no errors (Runtime → Run all)
- [X] No client names, URLs, or private queries anywhere
- [X] My claims use careful words: observed, measured, directional, decision-support
- [X] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.